name: example
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  zplayer:
    path: ../

  media_kit: ^1.1.7
  media_kit_video: ^1.1.8
  media_kit_libs_video: ^1.0.1
  media_kit_libs_macos_video: ^1.1.3
  media_kit_libs_ios_video: ^1.1.3

  media_cache_manager:
    git:
      url: https://github.com/mohamadlounnas/media_cache_manager.git

  youtube_explode_dart: ^2.0.2
  flutter_cache: ^0.1.0

  shared_preferences: ^2.2.0

  http_extensions_cache: ^1.0.0
  http_extensions: ^1.0.0
  logging: ^1.2.0

  dio_cache_interceptor: ^3.4.2
  dio_cache_interceptor_hive_store: ^3.2.1
  dio: ^5.3.2


# override dependencies
dependency_overrides:
  http: ^1.1.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
